### PR TITLE
Add1st style script structure

### PR DESCRIPTION
**Pull request by alef-garrido**
- Create a collection that keeps a list of books (hint: you can use an array of objects for that).
- Create a function to add a new book to the collection, with title and author.
- Create a function to remove a book from the collection (hint: you can use the array filter() method).
- Display all books saved in the collection in the top part of the page.
- Make sure that when a user clicks the "Add" button:
- A new book is added to the collection.
- The new book is displayed in the page.
- Make sure that when a user clicks the "Remove" button:
- The correct book is removed from the collection.
- The correct book dissapears from the page.
- Make sure that data is preserved in the browser's memory by using localStorage.
- To debug your application, you can use console.log(). Remember to remove debugging code before pushing your code to the remote repository.

### CODE REVIEW

**Review by mricanho — CHANGES_REQUESTED** [review]
# WRONG REVIEW

Hi @alef-garrido, 

Good commit messages, PR description and you are following the git-flow, good job.

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [x] Update your README file and put instructions about how to run your app locally, this is super important for all your present and future projects.

- [x] I can see your JS code, and it makes sense, at first sight, I can't see any error, but I need to run your project locally, the thing is you forgot to add the package.json and the webpack.config, without these files we can't run the project as it is. Please, add them.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

easyday

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by alef-garrido** [comment]
Hi @mricanho, thank you for your time reviewing my PR.
I just wanted to ask for some clarification because I have no idea of what you're mentioning I'm supposed to do.
So far I have never added a package.json to any of my projects nor have I ever used Webpack. I know there is a lesson further this week about that but I didn't see anything about that in the requirements for this PR. 
Can you explain please? Or should I request another review?

**Comment by mricanho** [comment]
> Hi @mricanho, thank you for your time reviewing my PR.
> I just wanted to ask for some clarification because I have no idea of what you're mentioning I'm supposed to do.
> So far I have never added a package.json to any of my projects nor have I ever used Webpack. I know there is a lesson further this week about that but I didn't see anything about it in the requirements for this PR.
> Can you explain please? Or should I request another review?

Hi @alef-garrido! 

Can you share the link to the lesson, please? First we need to make sure that we are not writing about different things, [is this the link of the lesson?](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)

**Comment by alef-garrido** [comment]
> > Hi @mricanho, thank you for your time reviewing my PR.
> > I just wanted to ask for some clarification because I have no idea of what you're mentioning I'm supposed to do.
> > So far I have never added a package.json to any of my projects nor have I ever used Webpack. I know there is a lesson further this week about that but I didn't see anything about it in the requirements for this PR.
> > Can you explain please? Or should I request another review?
> 
> Hi @alef-garrido!
> 
> Can you share the link to the lesson, please? First we need to make sure that we are not writing about different things, [is this the link of the lesson?](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)

Sure thing, this is it: 
https://github.com/microverseinc/curriculum-javascript/blob/main/books/m1_plain_js_objects.md

**Comment by mricanho** [comment]
> > > Hi @mricanho, thank you for your time reviewing my PR.
> > > I just wanted to ask for some clarification because I have no idea of what you're mentioning I'm supposed to do.
> > > So far I have never added a package.json to any of my projects nor have I ever used Webpack. I know there is a lesson further this week about that but I didn't see anything about it in the requirements for this PR.
> > > Can you explain please? Or should I request another review?
> > 
> > 
> > Hi @alef-garrido!
> > Can you share the link to the lesson, please? First we need to make sure that we are not writing about different things, [is this the link of the lesson?](https://github.com/microverseinc/curriculum-javascript/blob/main/todo-list/m1_list_structure.md)
> 
> Sure thing, this is it:
> https://github.com/microverseinc/curriculum-javascript/blob/main/books/m1_plain_js_objects.md

You are totally right, my fault, I was super confused with another group of students and projects.

Give 5 minutes and I'm gonna review it again.

sorry

**Comment by alef-garrido** [comment]
https://media.giphy.com/media/3o6Mb9EC7mNqXl9x7y/giphy.gif

**Comment by alef-garrido** [comment]
Okok!

**Review by mricanho — CHANGES_REQUESTED** [review]
Hi again @alef-garrido, 

Good job so far! 🔥🔥 Your project's almost done, your app it's up and running, nice use of local storage and the tricky delete action, the behavior it's the right one, nothing more to add here.

There are some issues that you still need to work on to go to the next project but you are almost there!

 ## Required Changes ♻️

- [ ] Just a minor fix to your README file and you are good to go, add instructions to run your project locally, and that's it. [Check this repository ](https://github.com/mricanho/To-do-list#how-to-start-the-project-from-your-local-enviroment)for references.

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

almostthere

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by bellom** [comment]
@alef-garrido @mricanho Wow you guys were so professional about the comments, you made me 😄 .

Keep it up, guys 🙏 👍

**Review by bellom — APPROVED** [review]
## Hi @alef-garrido  :clap: 

**Great work making all the necessary corrections from the previous review.**

# Status: Approved 👍 

## Congratulation :+1:  
_Go ahead and merge to dev and don't forget to submit the project completion form.
Good luck in the next project :slightly_smiling_face:_ 

**Best**

**Pull request merged**
